--***** CRIANDO BANCO DE DADOS *****
--***** BASE DE TABELAS *****
CREATE DATABASE DBTABELA
AS PERMANENT = 60e6, -- 60MB
    SPOOL = 120e6; -- 120MB;
-- *****BASE DE VIEWs*****
CREATE DATABASE DBVIEW
AS PERMANENT = 0, 
    SPOOL = 0; ;
 

    
--***** GRANT DE SELECT ENTRE BASES *****
GRANT SELECT ON DBTABELA TO DBVIEW WITH GRANT OPTION;

    
--***** TABELAS *****
CREATE MULTISET TABLE DBTABELA.PRODUTOS
(
ID INT,
NOME VARCHAR(100),
PRECO FLOAT
)NO PRIMARY INDEX;


CREATE MULTISET TABLE DBTABELA.CLIENTE (
	ID INT ,
	CPF CHAR(11),
	NOME VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(35) NOT NULL)
	NO PRIMARY INDEX;
	
	
--***** TABELA PARA USUÁRIOS COM PERMISSÃO DE LEITURA NA VIEW PESSOA *****
CREATE MULTISET TABLE DBTABELA.LEITURA_LIBERADA (
   LOGIN VARCHAR(40)
   );

	
--*****INSERT*****
INSERT INTO DBTABELA.PRODUTOS (ID,NOME,PRECO)VALUES( 1,'FEIJAO',3);
INSERT INTO DBTABELA.PRODUTOS (ID,NOME,PRECO)VALUES(2,'ARROZ SINHA',5);
INSERT INTO DBTABELA.PRODUTOS (ID,NOME,PRECO)VALUES(3,'ARROZ DEDE',9);
INSERT INTO DBTABELA.PRODUTOS (ID,NOME,PRECO)VALUES(4,'PARAFUSO',8);

INSERT INTO DBTABELA.CLIENTE (ID,CPF,NOME,CIDADE)VALUES(1,'60780056000','CARLOS J','EZRAUHULL');
INSERT INTO DBTABELA.CLIENTE (ID,CPF,NOME,CIDADE)VALUES(2,'65293217054','JOAO CARLOS','BRISWELL');
INSERT INTO DBTABELA.CLIENTE (ID,CPF,NOME,CIDADE)VALUES(3,'51931098026','MECIE','GREKA');
INSERT INTO DBTABELA.CLIENTE (ID,CPF,NOME,CIDADE)VALUES(4,'63841178006','VIDU','VIDU');

INSERT INTO DBTABELA.LEITURA_LIBERADA (LOGIN) VALUES('TESTE');


--***** CRIANDO USUÁRIO *****
CREATE USER TESTE  
AS
PERMANENT = 10000
PASSWORD = TESTE;

CREATE USER TESTE2  
AS
PERMANENT = 10000
PASSWORD = TESTE2;

--*****GRANT DE SELECT NA BASE DE VIEW***** 

GRANT SELECT ON DBVIEW TO TESTE;
GRANT SELECT ON DBVIEW TO TESTE2;


--*****CRIANDO A VIEW*****

REPLACE VIEW DBVIEW.PRODUTOS AS
(
SEL 
	ID,
	NOME,
	PRECO
	FROM DBTABELA.PRODUTOS
);

--***** View criada com validador de permissão*****
	/* ***** A tabela LEITURA_LIBERADA serve para validar se o usuário pode ou não ver o dado, o campo "user" pegando o login do usuário que está executando a query.
	 Se o usuário não tiver permissão a view não retorna nada******/
REPLACE VIEW DBVIEW.CLIENTE 
AS
(
SEL
	ID,
	CPF,
	NOME,
	CIDADE
   FROM DBTABELA.CLIENTE 
   WHERE (USER) = (SEL LOGIN  FROM DBTABELA.LEITURA_LIBERADA
 WHERE  LOGIN = (USER))
);

--*****Execute o seguinte select com o usuário TESTE,TESTE2 E DBC*****

SEL * FROM DBVIEW.PRODUTOS;
SEL * FROM DBVIEW.CLIENTE;

--*****Repare que os usuários TESTE,TESTE2 e DBC possuem select em toda a base DBVIEW, porém apenas o usuário TESTE consegue ver os dados da view DBVIEW.CLIENTE*****